// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGaraOto.Models;

#nullable disable

namespace QuanLyGaraOto.Migrations
{
    [DbContext(typeof(GaraDbContext))]
    [Migration("20260528171419_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyGaraOto.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaCTPN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTPN"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("MaVTPT")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaCTPN");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaVTPT");

                    b.ToTable("CT_PHIEUNHAP");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.ChiTietPhieuSuaChua", b =>
                {
                    b.Property<int>("MaCTSC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTSC"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaPhieuSuaChua")
                        .HasColumnType("int");

                    b.Property<int?>("MaTienCong")
                        .HasColumnType("int");

                    b.Property<int?>("MaVTPT")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungSuaChua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaCTSC");

                    b.HasIndex("MaPhieuSuaChua");

                    b.HasIndex("MaTienCong");

                    b.HasIndex("MaVTPT");

                    b.ToTable("CT_PHIEUSUACHUA");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.HieuXe", b =>
                {
                    b.Property<int>("MaHieuXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHieuXe"));

                    b.Property<string>("TenHieuXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHieuXe");

                    b.ToTable("HIEUXE");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NGUOIDUNG");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuNhap");

                    b.ToTable("PHIEUNHAP");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuSuaChua", b =>
                {
                    b.Property<int>("MaPhieuSuaChua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuSuaChua"));

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySuaChua")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.HasKey("MaPhieuSuaChua");

                    b.HasIndex("MaXe");

                    b.ToTable("PHIEUSUACHUA");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuThuTien", b =>
                {
                    b.Property<int>("MaPhieuThuTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuThuTien"));

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThuTien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienThu")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaPhieuThuTien");

                    b.HasIndex("MaXe");

                    b.ToTable("PHIEUTHUTIEN");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.ThamSo", b =>
                {
                    b.Property<string>("TenThamSo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenThamSo");

                    b.ToTable("THAMSO");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.TienCong", b =>
                {
                    b.Property<int>("MaTienCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienCong"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TenTienCong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTienCong");

                    b.ToTable("TIENCONG");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VAITRO");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.VatTuPhuTung", b =>
                {
                    b.Property<int>("MaVTPT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVTPT"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenVTPT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVTPT");

                    b.ToTable("VATTUPHUTUNG");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.Xe", b =>
                {
                    b.Property<int>("MaXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXe"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHieuXe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChuXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TienNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.HasKey("MaXe");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.HasIndex("MaHieuXe");

                    b.ToTable("XE");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("DanhSachCTPhieuNhap")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGaraOto.Models.VatTuPhuTung", "VatTuPhuTung")
                        .WithMany("DanhSachCTPhieuNhap")
                        .HasForeignKey("MaVTPT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("VatTuPhuTung");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.ChiTietPhieuSuaChua", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.PhieuSuaChua", "PhieuSuaChua")
                        .WithMany("DanhSachCTPhieuSuaChua")
                        .HasForeignKey("MaPhieuSuaChua")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGaraOto.Models.TienCong", "TienCong")
                        .WithMany("DanhSachCTPhieuSuaChua")
                        .HasForeignKey("MaTienCong")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyGaraOto.Models.VatTuPhuTung", "VatTuPhuTung")
                        .WithMany("DanhSachCTPhieuSuaChua")
                        .HasForeignKey("MaVTPT")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhieuSuaChua");

                    b.Navigation("TienCong");

                    b.Navigation("VatTuPhuTung");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.VaiTro", "VaiTro")
                        .WithMany("DanhSachNguoiDung")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuSuaChua", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.Xe", "Xe")
                        .WithMany("DanhSachPhieuSuaChua")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuThuTien", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.Xe", "Xe")
                        .WithMany("DanhSachPhieuThuTien")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.Xe", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.HieuXe", "HieuXe")
                        .WithMany("DanhSachXe")
                        .HasForeignKey("MaHieuXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HieuXe");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.HieuXe", b =>
                {
                    b.Navigation("DanhSachXe");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuNhap", b =>
                {
                    b.Navigation("DanhSachCTPhieuNhap");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuSuaChua", b =>
                {
                    b.Navigation("DanhSachCTPhieuSuaChua");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.TienCong", b =>
                {
                    b.Navigation("DanhSachCTPhieuSuaChua");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.VaiTro", b =>
                {
                    b.Navigation("DanhSachNguoiDung");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.VatTuPhuTung", b =>
                {
                    b.Navigation("DanhSachCTPhieuNhap");

                    b.Navigation("DanhSachCTPhieuSuaChua");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.Xe", b =>
                {
                    b.Navigation("DanhSachPhieuSuaChua");

                    b.Navigation("DanhSachPhieuThuTien");
                });
#pragma warning restore 612, 618
        }
    }
}
