// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGaraOto.Models;

#nullable disable

namespace QuanLyGaraOto.Migrations
{
    [DbContext(typeof(GaraDbContext))]
    [Migration("20260606042307_KhopBaoCaoGiuaKi")]
    partial class KhopBaoCaoGiuaKi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyGaraOto.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaCTPN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTPN"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("MaVTPT")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaCTPN");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaVTPT");

                    b.ToTable("CT_PHIEUNHAP");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.ChiTietPhieuSuaChua", b =>
                {
                    b.Property<int>("MaCTSC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTSC"));

                    b.Property<decimal>("ChiPhiTienCong")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TienCong");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaPhieuSuaChua")
                        .HasColumnType("int");

                    b.Property<int?>("MaTienCong")
                        .HasColumnType("int");

                    b.Property<int?>("MaVTPT")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungSuaChua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaCTSC");

                    b.HasIndex("MaPhieuSuaChua");

                    b.HasIndex("MaTienCong");

                    b.HasIndex("MaVTPT");

                    b.ToTable("CT_PHIEUSUACHUA");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.HieuXe", b =>
                {
                    b.Property<int>("MaHieuXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHieuXe"));

                    b.Property<string>("TenHieuXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHieuXe");

                    b.ToTable("HIEUXE");

                    b.HasData(
                        new
                        {
                            MaHieuXe = 1,
                            TenHieuXe = "Toyota"
                        },
                        new
                        {
                            MaHieuXe = 2,
                            TenHieuXe = "Honda"
                        },
                        new
                        {
                            MaHieuXe = 3,
                            TenHieuXe = "Ford"
                        },
                        new
                        {
                            MaHieuXe = 4,
                            TenHieuXe = "Hyundai"
                        },
                        new
                        {
                            MaHieuXe = 5,
                            TenHieuXe = "Kia"
                        },
                        new
                        {
                            MaHieuXe = 6,
                            TenHieuXe = "Mazda"
                        },
                        new
                        {
                            MaHieuXe = 7,
                            TenHieuXe = "Mitsubishi"
                        },
                        new
                        {
                            MaHieuXe = 8,
                            TenHieuXe = "Nissan"
                        },
                        new
                        {
                            MaHieuXe = 9,
                            TenHieuXe = "Chevrolet"
                        },
                        new
                        {
                            MaHieuXe = 10,
                            TenHieuXe = "Suzuki"
                        });
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NGUOIDUNG");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            MaVaiTro = 1,
                            MatKhau = "admin123",
                            TenDangNhap = "admin",
                            TenNguoiDung = "Quản Lý"
                        },
                        new
                        {
                            MaNguoiDung = 2,
                            MaVaiTro = 2,
                            MatKhau = "nv123",
                            TenDangNhap = "nhanvien",
                            TenNguoiDung = "Nhân Viên"
                        });
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.HasKey("MaPhieuNhap");

                    b.ToTable("PHIEUNHAP");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuSuaChua", b =>
                {
                    b.Property<int>("MaPhieuSuaChua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuSuaChua"));

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySuaChua")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienGiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TienThu")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.HasKey("MaPhieuSuaChua");

                    b.HasIndex("MaXe");

                    b.ToTable("PHIEUSUACHUA");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuThuTien", b =>
                {
                    b.Property<int>("MaPhieuThuTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuThuTien"));

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThuTien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienThu")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TienNoTruocThu")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaPhieuThuTien");

                    b.HasIndex("MaXe");

                    b.ToTable("PHIEUTHUTIEN");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.ThamSo", b =>
                {
                    b.Property<string>("TenThamSo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenThamSo");

                    b.ToTable("THAMSO");

                    b.HasData(
                        new
                        {
                            TenThamSo = "SoXeSuaChuaToiDa",
                            GiaTri = "30"
                        },
                        new
                        {
                            TenThamSo = "TiLeDonGiaBan",
                            GiaTri = "1.05"
                        },
                        new
                        {
                            TenThamSo = "ApDungQDKiemTraSoTienThu",
                            GiaTri = "1"
                        });
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.TienCong", b =>
                {
                    b.Property<int>("MaTienCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienCong"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TenTienCong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTienCong");

                    b.ToTable("TIENCONG");

                    b.HasData(
                        new
                        {
                            MaTienCong = 1,
                            DonGia = 0m,
                            TenTienCong = "Không tính công"
                        },
                        new
                        {
                            MaTienCong = 2,
                            DonGia = 0m,
                            TenTienCong = "Bảo hành"
                        },
                        new
                        {
                            MaTienCong = 3,
                            DonGia = 405000m,
                            TenTienCong = "Thay nhớt máy"
                        },
                        new
                        {
                            MaTienCong = 4,
                            DonGia = 313000m,
                            TenTienCong = "Thay kim phun"
                        },
                        new
                        {
                            MaTienCong = 5,
                            DonGia = 443000m,
                            TenTienCong = "Thay phanh 4 bánh"
                        },
                        new
                        {
                            MaTienCong = 6,
                            DonGia = 498000m,
                            TenTienCong = "Thay thước lái"
                        },
                        new
                        {
                            MaTienCong = 7,
                            DonGia = 221000m,
                            TenTienCong = "Thay dàn lạnh"
                        },
                        new
                        {
                            MaTienCong = 8,
                            DonGia = 247000m,
                            TenTienCong = "Thay bugi"
                        },
                        new
                        {
                            MaTienCong = 9,
                            DonGia = 138000m,
                            TenTienCong = "Thay lọc gió"
                        },
                        new
                        {
                            MaTienCong = 10,
                            DonGia = 312000m,
                            TenTienCong = "Thay curoa"
                        },
                        new
                        {
                            MaTienCong = 11,
                            DonGia = 196000m,
                            TenTienCong = "Thay bơm nước"
                        },
                        new
                        {
                            MaTienCong = 12,
                            DonGia = 333000m,
                            TenTienCong = "Thay hộp số"
                        },
                        new
                        {
                            MaTienCong = 13,
                            DonGia = 57000m,
                            TenTienCong = "Thay điều hòa"
                        },
                        new
                        {
                            MaTienCong = 14,
                            DonGia = 257000m,
                            TenTienCong = "Thay bơm xăng"
                        },
                        new
                        {
                            MaTienCong = 15,
                            DonGia = 175000m,
                            TenTienCong = "Vệ sinh nhớt máy"
                        },
                        new
                        {
                            MaTienCong = 16,
                            DonGia = 237000m,
                            TenTienCong = "Vệ sinh kim phun"
                        },
                        new
                        {
                            MaTienCong = 17,
                            DonGia = 433000m,
                            TenTienCong = "Vệ sinh phanh 4 bánh"
                        },
                        new
                        {
                            MaTienCong = 18,
                            DonGia = 199000m,
                            TenTienCong = "Vệ sinh thước lái"
                        },
                        new
                        {
                            MaTienCong = 19,
                            DonGia = 344000m,
                            TenTienCong = "Vệ sinh dàn lạnh"
                        },
                        new
                        {
                            MaTienCong = 20,
                            DonGia = 460000m,
                            TenTienCong = "Vệ sinh bugi"
                        },
                        new
                        {
                            MaTienCong = 21,
                            DonGia = 453000m,
                            TenTienCong = "Vệ sinh lọc gió"
                        },
                        new
                        {
                            MaTienCong = 22,
                            DonGia = 472000m,
                            TenTienCong = "Vệ sinh curoa"
                        },
                        new
                        {
                            MaTienCong = 23,
                            DonGia = 189000m,
                            TenTienCong = "Vệ sinh bơm nước"
                        },
                        new
                        {
                            MaTienCong = 24,
                            DonGia = 176000m,
                            TenTienCong = "Vệ sinh hộp số"
                        },
                        new
                        {
                            MaTienCong = 25,
                            DonGia = 51000m,
                            TenTienCong = "Vệ sinh điều hòa"
                        },
                        new
                        {
                            MaTienCong = 26,
                            DonGia = 430000m,
                            TenTienCong = "Vệ sinh bơm xăng"
                        },
                        new
                        {
                            MaTienCong = 27,
                            DonGia = 134000m,
                            TenTienCong = "Bảo dưỡng nhớt máy"
                        },
                        new
                        {
                            MaTienCong = 28,
                            DonGia = 425000m,
                            TenTienCong = "Bảo dưỡng kim phun"
                        },
                        new
                        {
                            MaTienCong = 29,
                            DonGia = 63000m,
                            TenTienCong = "Bảo dưỡng phanh 4 bánh"
                        },
                        new
                        {
                            MaTienCong = 30,
                            DonGia = 316000m,
                            TenTienCong = "Bảo dưỡng thước lái"
                        },
                        new
                        {
                            MaTienCong = 31,
                            DonGia = 417000m,
                            TenTienCong = "Bảo dưỡng dàn lạnh"
                        },
                        new
                        {
                            MaTienCong = 32,
                            DonGia = 428000m,
                            TenTienCong = "Bảo dưỡng bugi"
                        },
                        new
                        {
                            MaTienCong = 33,
                            DonGia = 201000m,
                            TenTienCong = "Bảo dưỡng lọc gió"
                        },
                        new
                        {
                            MaTienCong = 34,
                            DonGia = 359000m,
                            TenTienCong = "Bảo dưỡng curoa"
                        },
                        new
                        {
                            MaTienCong = 35,
                            DonGia = 497000m,
                            TenTienCong = "Bảo dưỡng bơm nước"
                        },
                        new
                        {
                            MaTienCong = 36,
                            DonGia = 52000m,
                            TenTienCong = "Bảo dưỡng hộp số"
                        },
                        new
                        {
                            MaTienCong = 37,
                            DonGia = 432000m,
                            TenTienCong = "Bảo dưỡng điều hòa"
                        },
                        new
                        {
                            MaTienCong = 38,
                            DonGia = 363000m,
                            TenTienCong = "Bảo dưỡng bơm xăng"
                        },
                        new
                        {
                            MaTienCong = 39,
                            DonGia = 304000m,
                            TenTienCong = "Cân chỉnh nhớt máy"
                        },
                        new
                        {
                            MaTienCong = 40,
                            DonGia = 227000m,
                            TenTienCong = "Cân chỉnh kim phun"
                        },
                        new
                        {
                            MaTienCong = 41,
                            DonGia = 90000m,
                            TenTienCong = "Cân chỉnh phanh 4 bánh"
                        },
                        new
                        {
                            MaTienCong = 42,
                            DonGia = 463000m,
                            TenTienCong = "Cân chỉnh thước lái"
                        },
                        new
                        {
                            MaTienCong = 43,
                            DonGia = 301000m,
                            TenTienCong = "Cân chỉnh dàn lạnh"
                        },
                        new
                        {
                            MaTienCong = 44,
                            DonGia = 58000m,
                            TenTienCong = "Cân chỉnh bugi"
                        },
                        new
                        {
                            MaTienCong = 45,
                            DonGia = 123000m,
                            TenTienCong = "Cân chỉnh lọc gió"
                        },
                        new
                        {
                            MaTienCong = 46,
                            DonGia = 457000m,
                            TenTienCong = "Cân chỉnh curoa"
                        },
                        new
                        {
                            MaTienCong = 47,
                            DonGia = 491000m,
                            TenTienCong = "Cân chỉnh bơm nước"
                        },
                        new
                        {
                            MaTienCong = 48,
                            DonGia = 234000m,
                            TenTienCong = "Cân chỉnh hộp số"
                        },
                        new
                        {
                            MaTienCong = 49,
                            DonGia = 350000m,
                            TenTienCong = "Cân chỉnh điều hòa"
                        },
                        new
                        {
                            MaTienCong = 50,
                            DonGia = 310000m,
                            TenTienCong = "Cân chỉnh bơm xăng"
                        },
                        new
                        {
                            MaTienCong = 51,
                            DonGia = 473000m,
                            TenTienCong = "Phục hồi nhớt máy"
                        },
                        new
                        {
                            MaTienCong = 52,
                            DonGia = 425000m,
                            TenTienCong = "Phục hồi kim phun"
                        },
                        new
                        {
                            MaTienCong = 53,
                            DonGia = 418000m,
                            TenTienCong = "Phục hồi phanh 4 bánh"
                        },
                        new
                        {
                            MaTienCong = 54,
                            DonGia = 142000m,
                            TenTienCong = "Phục hồi thước lái"
                        },
                        new
                        {
                            MaTienCong = 55,
                            DonGia = 103000m,
                            TenTienCong = "Phục hồi dàn lạnh"
                        },
                        new
                        {
                            MaTienCong = 56,
                            DonGia = 87000m,
                            TenTienCong = "Phục hồi bugi"
                        },
                        new
                        {
                            MaTienCong = 57,
                            DonGia = 372000m,
                            TenTienCong = "Phục hồi lọc gió"
                        },
                        new
                        {
                            MaTienCong = 58,
                            DonGia = 279000m,
                            TenTienCong = "Phục hồi curoa"
                        },
                        new
                        {
                            MaTienCong = 59,
                            DonGia = 311000m,
                            TenTienCong = "Phục hồi bơm nước"
                        },
                        new
                        {
                            MaTienCong = 60,
                            DonGia = 62000m,
                            TenTienCong = "Phục hồi hộp số"
                        },
                        new
                        {
                            MaTienCong = 61,
                            DonGia = 413000m,
                            TenTienCong = "Phục hồi điều hòa"
                        },
                        new
                        {
                            MaTienCong = 62,
                            DonGia = 296000m,
                            TenTienCong = "Phục hồi bơm xăng"
                        },
                        new
                        {
                            MaTienCong = 63,
                            DonGia = 234000m,
                            TenTienCong = "Kiểm tra nhớt máy"
                        },
                        new
                        {
                            MaTienCong = 64,
                            DonGia = 321000m,
                            TenTienCong = "Kiểm tra kim phun"
                        },
                        new
                        {
                            MaTienCong = 65,
                            DonGia = 395000m,
                            TenTienCong = "Kiểm tra phanh 4 bánh"
                        },
                        new
                        {
                            MaTienCong = 66,
                            DonGia = 268000m,
                            TenTienCong = "Kiểm tra thước lái"
                        },
                        new
                        {
                            MaTienCong = 67,
                            DonGia = 181000m,
                            TenTienCong = "Kiểm tra dàn lạnh"
                        },
                        new
                        {
                            MaTienCong = 68,
                            DonGia = 198000m,
                            TenTienCong = "Kiểm tra bugi"
                        },
                        new
                        {
                            MaTienCong = 69,
                            DonGia = 259000m,
                            TenTienCong = "Kiểm tra lọc gió"
                        },
                        new
                        {
                            MaTienCong = 70,
                            DonGia = 173000m,
                            TenTienCong = "Kiểm tra curoa"
                        },
                        new
                        {
                            MaTienCong = 71,
                            DonGia = 305000m,
                            TenTienCong = "Kiểm tra bơm nước"
                        },
                        new
                        {
                            MaTienCong = 72,
                            DonGia = 119000m,
                            TenTienCong = "Kiểm tra hộp số"
                        },
                        new
                        {
                            MaTienCong = 73,
                            DonGia = 394000m,
                            TenTienCong = "Kiểm tra điều hòa"
                        },
                        new
                        {
                            MaTienCong = 74,
                            DonGia = 166000m,
                            TenTienCong = "Kiểm tra bơm xăng"
                        },
                        new
                        {
                            MaTienCong = 75,
                            DonGia = 419000m,
                            TenTienCong = "Đánh bóng nhớt máy"
                        },
                        new
                        {
                            MaTienCong = 76,
                            DonGia = 490000m,
                            TenTienCong = "Đánh bóng kim phun"
                        },
                        new
                        {
                            MaTienCong = 77,
                            DonGia = 220000m,
                            TenTienCong = "Đánh bóng phanh 4 bánh"
                        },
                        new
                        {
                            MaTienCong = 78,
                            DonGia = 180000m,
                            TenTienCong = "Đánh bóng thước lái"
                        },
                        new
                        {
                            MaTienCong = 79,
                            DonGia = 102000m,
                            TenTienCong = "Đánh bóng dàn lạnh"
                        },
                        new
                        {
                            MaTienCong = 80,
                            DonGia = 94000m,
                            TenTienCong = "Đánh bóng bugi"
                        },
                        new
                        {
                            MaTienCong = 81,
                            DonGia = 438000m,
                            TenTienCong = "Đánh bóng lọc gió"
                        },
                        new
                        {
                            MaTienCong = 82,
                            DonGia = 400000m,
                            TenTienCong = "Đánh bóng curoa"
                        },
                        new
                        {
                            MaTienCong = 83,
                            DonGia = 125000m,
                            TenTienCong = "Đánh bóng bơm nước"
                        },
                        new
                        {
                            MaTienCong = 84,
                            DonGia = 253000m,
                            TenTienCong = "Đánh bóng hộp số"
                        },
                        new
                        {
                            MaTienCong = 85,
                            DonGia = 343000m,
                            TenTienCong = "Đánh bóng điều hòa"
                        },
                        new
                        {
                            MaTienCong = 86,
                            DonGia = 491000m,
                            TenTienCong = "Đánh bóng bơm xăng"
                        },
                        new
                        {
                            MaTienCong = 87,
                            DonGia = 60000m,
                            TenTienCong = "Sơn nhớt máy"
                        },
                        new
                        {
                            MaTienCong = 88,
                            DonGia = 109000m,
                            TenTienCong = "Sơn kim phun"
                        },
                        new
                        {
                            MaTienCong = 89,
                            DonGia = 306000m,
                            TenTienCong = "Sơn phanh 4 bánh"
                        },
                        new
                        {
                            MaTienCong = 90,
                            DonGia = 459000m,
                            TenTienCong = "Sơn thước lái"
                        },
                        new
                        {
                            MaTienCong = 91,
                            DonGia = 180000m,
                            TenTienCong = "Sơn dàn lạnh"
                        },
                        new
                        {
                            MaTienCong = 92,
                            DonGia = 203000m,
                            TenTienCong = "Sơn bugi"
                        },
                        new
                        {
                            MaTienCong = 93,
                            DonGia = 101000m,
                            TenTienCong = "Sơn lọc gió"
                        },
                        new
                        {
                            MaTienCong = 94,
                            DonGia = 292000m,
                            TenTienCong = "Sơn curoa"
                        },
                        new
                        {
                            MaTienCong = 95,
                            DonGia = 314000m,
                            TenTienCong = "Sơn bơm nước"
                        },
                        new
                        {
                            MaTienCong = 96,
                            DonGia = 294000m,
                            TenTienCong = "Sơn hộp số"
                        },
                        new
                        {
                            MaTienCong = 97,
                            DonGia = 279000m,
                            TenTienCong = "Sơn điều hòa"
                        },
                        new
                        {
                            MaTienCong = 98,
                            DonGia = 480000m,
                            TenTienCong = "Sơn bơm xăng"
                        },
                        new
                        {
                            MaTienCong = 99,
                            DonGia = 163000m,
                            TenTienCong = "Gò nhớt máy"
                        },
                        new
                        {
                            MaTienCong = 100,
                            DonGia = 355000m,
                            TenTienCong = "Gò kim phun"
                        });
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VAITRO");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "QuanLy"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "NhanVien"
                        });
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.VatTuPhuTung", b =>
                {
                    b.Property<int>("MaVTPT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVTPT"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenVTPT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVTPT");

                    b.ToTable("VATTUPHUTUNG");

                    b.HasData(
                        new
                        {
                            MaVTPT = 1,
                            DonGia = 216000m,
                            SoLuongTon = 38,
                            TenVTPT = "Bugi Michelin Loại 1"
                        },
                        new
                        {
                            MaVTPT = 2,
                            DonGia = 803000m,
                            SoLuongTon = 33,
                            TenVTPT = "Bugi Michelin Loại 2"
                        },
                        new
                        {
                            MaVTPT = 3,
                            DonGia = 69000m,
                            SoLuongTon = 23,
                            TenVTPT = "Bugi Michelin Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 4,
                            DonGia = 1170000m,
                            SoLuongTon = 44,
                            TenVTPT = "Bugi Denso Loại 1"
                        },
                        new
                        {
                            MaVTPT = 5,
                            DonGia = 601000m,
                            SoLuongTon = 35,
                            TenVTPT = "Bugi Denso Loại 2"
                        },
                        new
                        {
                            MaVTPT = 6,
                            DonGia = 680000m,
                            SoLuongTon = 35,
                            TenVTPT = "Bugi Denso Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 7,
                            DonGia = 98000m,
                            SoLuongTon = 29,
                            TenVTPT = "Bugi Bosch Loại 1"
                        },
                        new
                        {
                            MaVTPT = 8,
                            DonGia = 1101000m,
                            SoLuongTon = 12,
                            TenVTPT = "Bugi Bosch Loại 2"
                        },
                        new
                        {
                            MaVTPT = 9,
                            DonGia = 1020000m,
                            SoLuongTon = 45,
                            TenVTPT = "Bugi Bosch Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 10,
                            DonGia = 728000m,
                            SoLuongTon = 10,
                            TenVTPT = "Bugi Brembo Loại 1"
                        },
                        new
                        {
                            MaVTPT = 11,
                            DonGia = 1132000m,
                            SoLuongTon = 26,
                            TenVTPT = "Bugi Brembo Loại 2"
                        },
                        new
                        {
                            MaVTPT = 12,
                            DonGia = 134000m,
                            SoLuongTon = 14,
                            TenVTPT = "Bugi Brembo Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 13,
                            DonGia = 142000m,
                            SoLuongTon = 23,
                            TenVTPT = "Bugi NGK Loại 1"
                        },
                        new
                        {
                            MaVTPT = 14,
                            DonGia = 192000m,
                            SoLuongTon = 41,
                            TenVTPT = "Bugi NGK Loại 2"
                        },
                        new
                        {
                            MaVTPT = 15,
                            DonGia = 922000m,
                            SoLuongTon = 15,
                            TenVTPT = "Bugi NGK Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 16,
                            DonGia = 634000m,
                            SoLuongTon = 34,
                            TenVTPT = "Bugi Yuasa Loại 1"
                        },
                        new
                        {
                            MaVTPT = 17,
                            DonGia = 334000m,
                            SoLuongTon = 39,
                            TenVTPT = "Bugi Yuasa Loại 2"
                        },
                        new
                        {
                            MaVTPT = 18,
                            DonGia = 601000m,
                            SoLuongTon = 29,
                            TenVTPT = "Bugi Yuasa Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 19,
                            DonGia = 933000m,
                            SoLuongTon = 40,
                            TenVTPT = "Bugi Varta Loại 1"
                        },
                        new
                        {
                            MaVTPT = 20,
                            DonGia = 1437000m,
                            SoLuongTon = 17,
                            TenVTPT = "Bugi Varta Loại 2"
                        },
                        new
                        {
                            MaVTPT = 21,
                            DonGia = 516000m,
                            SoLuongTon = 11,
                            TenVTPT = "Bugi Varta Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 22,
                            DonGia = 258000m,
                            SoLuongTon = 23,
                            TenVTPT = "Bugi K&N Loại 1"
                        },
                        new
                        {
                            MaVTPT = 23,
                            DonGia = 97000m,
                            SoLuongTon = 18,
                            TenVTPT = "Bugi K&N Loại 2"
                        },
                        new
                        {
                            MaVTPT = 24,
                            DonGia = 1420000m,
                            SoLuongTon = 16,
                            TenVTPT = "Bugi K&N Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 25,
                            DonGia = 1324000m,
                            SoLuongTon = 40,
                            TenVTPT = "Bugi Mobil Loại 1"
                        },
                        new
                        {
                            MaVTPT = 26,
                            DonGia = 857000m,
                            SoLuongTon = 48,
                            TenVTPT = "Bugi Mobil Loại 2"
                        },
                        new
                        {
                            MaVTPT = 27,
                            DonGia = 886000m,
                            SoLuongTon = 44,
                            TenVTPT = "Bugi Mobil Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 28,
                            DonGia = 716000m,
                            SoLuongTon = 38,
                            TenVTPT = "Bugi Castrol Loại 1"
                        },
                        new
                        {
                            MaVTPT = 29,
                            DonGia = 975000m,
                            SoLuongTon = 26,
                            TenVTPT = "Bugi Castrol Loại 2"
                        },
                        new
                        {
                            MaVTPT = 30,
                            DonGia = 779000m,
                            SoLuongTon = 38,
                            TenVTPT = "Bugi Castrol Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 31,
                            DonGia = 383000m,
                            SoLuongTon = 50,
                            TenVTPT = "Lốp xe Michelin Loại 1"
                        },
                        new
                        {
                            MaVTPT = 32,
                            DonGia = 411000m,
                            SoLuongTon = 20,
                            TenVTPT = "Lốp xe Michelin Loại 2"
                        },
                        new
                        {
                            MaVTPT = 33,
                            DonGia = 373000m,
                            SoLuongTon = 44,
                            TenVTPT = "Lốp xe Michelin Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 34,
                            DonGia = 684000m,
                            SoLuongTon = 22,
                            TenVTPT = "Lốp xe Denso Loại 1"
                        },
                        new
                        {
                            MaVTPT = 35,
                            DonGia = 174000m,
                            SoLuongTon = 20,
                            TenVTPT = "Lốp xe Denso Loại 2"
                        },
                        new
                        {
                            MaVTPT = 36,
                            DonGia = 704000m,
                            SoLuongTon = 48,
                            TenVTPT = "Lốp xe Denso Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 37,
                            DonGia = 1379000m,
                            SoLuongTon = 21,
                            TenVTPT = "Lốp xe Bosch Loại 1"
                        },
                        new
                        {
                            MaVTPT = 38,
                            DonGia = 1058000m,
                            SoLuongTon = 39,
                            TenVTPT = "Lốp xe Bosch Loại 2"
                        },
                        new
                        {
                            MaVTPT = 39,
                            DonGia = 435000m,
                            SoLuongTon = 40,
                            TenVTPT = "Lốp xe Bosch Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 40,
                            DonGia = 160000m,
                            SoLuongTon = 44,
                            TenVTPT = "Lốp xe Brembo Loại 1"
                        },
                        new
                        {
                            MaVTPT = 41,
                            DonGia = 606000m,
                            SoLuongTon = 48,
                            TenVTPT = "Lốp xe Brembo Loại 2"
                        },
                        new
                        {
                            MaVTPT = 42,
                            DonGia = 1348000m,
                            SoLuongTon = 45,
                            TenVTPT = "Lốp xe Brembo Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 43,
                            DonGia = 879000m,
                            SoLuongTon = 29,
                            TenVTPT = "Lốp xe NGK Loại 1"
                        },
                        new
                        {
                            MaVTPT = 44,
                            DonGia = 66000m,
                            SoLuongTon = 24,
                            TenVTPT = "Lốp xe NGK Loại 2"
                        },
                        new
                        {
                            MaVTPT = 45,
                            DonGia = 444000m,
                            SoLuongTon = 37,
                            TenVTPT = "Lốp xe NGK Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 46,
                            DonGia = 1268000m,
                            SoLuongTon = 18,
                            TenVTPT = "Lốp xe Yuasa Loại 1"
                        },
                        new
                        {
                            MaVTPT = 47,
                            DonGia = 385000m,
                            SoLuongTon = 21,
                            TenVTPT = "Lốp xe Yuasa Loại 2"
                        },
                        new
                        {
                            MaVTPT = 48,
                            DonGia = 1443000m,
                            SoLuongTon = 23,
                            TenVTPT = "Lốp xe Yuasa Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 49,
                            DonGia = 1183000m,
                            SoLuongTon = 46,
                            TenVTPT = "Lốp xe Varta Loại 1"
                        },
                        new
                        {
                            MaVTPT = 50,
                            DonGia = 186000m,
                            SoLuongTon = 17,
                            TenVTPT = "Lốp xe Varta Loại 2"
                        },
                        new
                        {
                            MaVTPT = 51,
                            DonGia = 1170000m,
                            SoLuongTon = 36,
                            TenVTPT = "Lốp xe Varta Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 52,
                            DonGia = 164000m,
                            SoLuongTon = 35,
                            TenVTPT = "Lốp xe K&N Loại 1"
                        },
                        new
                        {
                            MaVTPT = 53,
                            DonGia = 457000m,
                            SoLuongTon = 35,
                            TenVTPT = "Lốp xe K&N Loại 2"
                        },
                        new
                        {
                            MaVTPT = 54,
                            DonGia = 78000m,
                            SoLuongTon = 22,
                            TenVTPT = "Lốp xe K&N Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 55,
                            DonGia = 246000m,
                            SoLuongTon = 40,
                            TenVTPT = "Lốp xe Mobil Loại 1"
                        },
                        new
                        {
                            MaVTPT = 56,
                            DonGia = 687000m,
                            SoLuongTon = 46,
                            TenVTPT = "Lốp xe Mobil Loại 2"
                        },
                        new
                        {
                            MaVTPT = 57,
                            DonGia = 535000m,
                            SoLuongTon = 36,
                            TenVTPT = "Lốp xe Mobil Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 58,
                            DonGia = 486000m,
                            SoLuongTon = 22,
                            TenVTPT = "Lốp xe Castrol Loại 1"
                        },
                        new
                        {
                            MaVTPT = 59,
                            DonGia = 199000m,
                            SoLuongTon = 25,
                            TenVTPT = "Lốp xe Castrol Loại 2"
                        },
                        new
                        {
                            MaVTPT = 60,
                            DonGia = 1035000m,
                            SoLuongTon = 41,
                            TenVTPT = "Lốp xe Castrol Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 61,
                            DonGia = 1259000m,
                            SoLuongTon = 12,
                            TenVTPT = "Má phanh Michelin Loại 1"
                        },
                        new
                        {
                            MaVTPT = 62,
                            DonGia = 94000m,
                            SoLuongTon = 26,
                            TenVTPT = "Má phanh Michelin Loại 2"
                        },
                        new
                        {
                            MaVTPT = 63,
                            DonGia = 638000m,
                            SoLuongTon = 20,
                            TenVTPT = "Má phanh Michelin Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 64,
                            DonGia = 1069000m,
                            SoLuongTon = 36,
                            TenVTPT = "Má phanh Denso Loại 1"
                        },
                        new
                        {
                            MaVTPT = 65,
                            DonGia = 507000m,
                            SoLuongTon = 25,
                            TenVTPT = "Má phanh Denso Loại 2"
                        },
                        new
                        {
                            MaVTPT = 66,
                            DonGia = 1403000m,
                            SoLuongTon = 25,
                            TenVTPT = "Má phanh Denso Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 67,
                            DonGia = 987000m,
                            SoLuongTon = 46,
                            TenVTPT = "Má phanh Bosch Loại 1"
                        },
                        new
                        {
                            MaVTPT = 68,
                            DonGia = 167000m,
                            SoLuongTon = 40,
                            TenVTPT = "Má phanh Bosch Loại 2"
                        },
                        new
                        {
                            MaVTPT = 69,
                            DonGia = 1288000m,
                            SoLuongTon = 20,
                            TenVTPT = "Má phanh Bosch Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 70,
                            DonGia = 903000m,
                            SoLuongTon = 48,
                            TenVTPT = "Má phanh Brembo Loại 1"
                        },
                        new
                        {
                            MaVTPT = 71,
                            DonGia = 698000m,
                            SoLuongTon = 39,
                            TenVTPT = "Má phanh Brembo Loại 2"
                        },
                        new
                        {
                            MaVTPT = 72,
                            DonGia = 382000m,
                            SoLuongTon = 31,
                            TenVTPT = "Má phanh Brembo Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 73,
                            DonGia = 390000m,
                            SoLuongTon = 48,
                            TenVTPT = "Má phanh NGK Loại 1"
                        },
                        new
                        {
                            MaVTPT = 74,
                            DonGia = 1301000m,
                            SoLuongTon = 33,
                            TenVTPT = "Má phanh NGK Loại 2"
                        },
                        new
                        {
                            MaVTPT = 75,
                            DonGia = 1458000m,
                            SoLuongTon = 37,
                            TenVTPT = "Má phanh NGK Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 76,
                            DonGia = 368000m,
                            SoLuongTon = 26,
                            TenVTPT = "Má phanh Yuasa Loại 1"
                        },
                        new
                        {
                            MaVTPT = 77,
                            DonGia = 359000m,
                            SoLuongTon = 23,
                            TenVTPT = "Má phanh Yuasa Loại 2"
                        },
                        new
                        {
                            MaVTPT = 78,
                            DonGia = 561000m,
                            SoLuongTon = 38,
                            TenVTPT = "Má phanh Yuasa Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 79,
                            DonGia = 938000m,
                            SoLuongTon = 37,
                            TenVTPT = "Má phanh Varta Loại 1"
                        },
                        new
                        {
                            MaVTPT = 80,
                            DonGia = 379000m,
                            SoLuongTon = 11,
                            TenVTPT = "Má phanh Varta Loại 2"
                        },
                        new
                        {
                            MaVTPT = 81,
                            DonGia = 1383000m,
                            SoLuongTon = 25,
                            TenVTPT = "Má phanh Varta Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 82,
                            DonGia = 1477000m,
                            SoLuongTon = 41,
                            TenVTPT = "Má phanh K&N Loại 1"
                        },
                        new
                        {
                            MaVTPT = 83,
                            DonGia = 1225000m,
                            SoLuongTon = 12,
                            TenVTPT = "Má phanh K&N Loại 2"
                        },
                        new
                        {
                            MaVTPT = 84,
                            DonGia = 414000m,
                            SoLuongTon = 28,
                            TenVTPT = "Má phanh K&N Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 85,
                            DonGia = 874000m,
                            SoLuongTon = 32,
                            TenVTPT = "Má phanh Mobil Loại 1"
                        },
                        new
                        {
                            MaVTPT = 86,
                            DonGia = 691000m,
                            SoLuongTon = 44,
                            TenVTPT = "Má phanh Mobil Loại 2"
                        },
                        new
                        {
                            MaVTPT = 87,
                            DonGia = 1196000m,
                            SoLuongTon = 39,
                            TenVTPT = "Má phanh Mobil Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 88,
                            DonGia = 499000m,
                            SoLuongTon = 15,
                            TenVTPT = "Má phanh Castrol Loại 1"
                        },
                        new
                        {
                            MaVTPT = 89,
                            DonGia = 1272000m,
                            SoLuongTon = 30,
                            TenVTPT = "Má phanh Castrol Loại 2"
                        },
                        new
                        {
                            MaVTPT = 90,
                            DonGia = 305000m,
                            SoLuongTon = 28,
                            TenVTPT = "Má phanh Castrol Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 91,
                            DonGia = 614000m,
                            SoLuongTon = 14,
                            TenVTPT = "Lọc nhớt Michelin Loại 1"
                        },
                        new
                        {
                            MaVTPT = 92,
                            DonGia = 1025000m,
                            SoLuongTon = 36,
                            TenVTPT = "Lọc nhớt Michelin Loại 2"
                        },
                        new
                        {
                            MaVTPT = 93,
                            DonGia = 271000m,
                            SoLuongTon = 31,
                            TenVTPT = "Lọc nhớt Michelin Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 94,
                            DonGia = 281000m,
                            SoLuongTon = 22,
                            TenVTPT = "Lọc nhớt Denso Loại 1"
                        },
                        new
                        {
                            MaVTPT = 95,
                            DonGia = 827000m,
                            SoLuongTon = 25,
                            TenVTPT = "Lọc nhớt Denso Loại 2"
                        },
                        new
                        {
                            MaVTPT = 96,
                            DonGia = 235000m,
                            SoLuongTon = 17,
                            TenVTPT = "Lọc nhớt Denso Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 97,
                            DonGia = 101000m,
                            SoLuongTon = 33,
                            TenVTPT = "Lọc nhớt Bosch Loại 1"
                        },
                        new
                        {
                            MaVTPT = 98,
                            DonGia = 93000m,
                            SoLuongTon = 12,
                            TenVTPT = "Lọc nhớt Bosch Loại 2"
                        },
                        new
                        {
                            MaVTPT = 99,
                            DonGia = 1103000m,
                            SoLuongTon = 29,
                            TenVTPT = "Lọc nhớt Bosch Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 100,
                            DonGia = 1089000m,
                            SoLuongTon = 16,
                            TenVTPT = "Lọc nhớt Brembo Loại 1"
                        },
                        new
                        {
                            MaVTPT = 101,
                            DonGia = 1052000m,
                            SoLuongTon = 27,
                            TenVTPT = "Lọc nhớt Brembo Loại 2"
                        },
                        new
                        {
                            MaVTPT = 102,
                            DonGia = 68000m,
                            SoLuongTon = 26,
                            TenVTPT = "Lọc nhớt Brembo Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 103,
                            DonGia = 372000m,
                            SoLuongTon = 25,
                            TenVTPT = "Lọc nhớt NGK Loại 1"
                        },
                        new
                        {
                            MaVTPT = 104,
                            DonGia = 936000m,
                            SoLuongTon = 29,
                            TenVTPT = "Lọc nhớt NGK Loại 2"
                        },
                        new
                        {
                            MaVTPT = 105,
                            DonGia = 90000m,
                            SoLuongTon = 19,
                            TenVTPT = "Lọc nhớt NGK Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 106,
                            DonGia = 1292000m,
                            SoLuongTon = 14,
                            TenVTPT = "Lọc nhớt Yuasa Loại 1"
                        },
                        new
                        {
                            MaVTPT = 107,
                            DonGia = 762000m,
                            SoLuongTon = 41,
                            TenVTPT = "Lọc nhớt Yuasa Loại 2"
                        },
                        new
                        {
                            MaVTPT = 108,
                            DonGia = 975000m,
                            SoLuongTon = 42,
                            TenVTPT = "Lọc nhớt Yuasa Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 109,
                            DonGia = 1068000m,
                            SoLuongTon = 23,
                            TenVTPT = "Lọc nhớt Varta Loại 1"
                        },
                        new
                        {
                            MaVTPT = 110,
                            DonGia = 935000m,
                            SoLuongTon = 21,
                            TenVTPT = "Lọc nhớt Varta Loại 2"
                        },
                        new
                        {
                            MaVTPT = 111,
                            DonGia = 1365000m,
                            SoLuongTon = 48,
                            TenVTPT = "Lọc nhớt Varta Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 112,
                            DonGia = 1369000m,
                            SoLuongTon = 17,
                            TenVTPT = "Lọc nhớt K&N Loại 1"
                        },
                        new
                        {
                            MaVTPT = 113,
                            DonGia = 677000m,
                            SoLuongTon = 20,
                            TenVTPT = "Lọc nhớt K&N Loại 2"
                        },
                        new
                        {
                            MaVTPT = 114,
                            DonGia = 1218000m,
                            SoLuongTon = 19,
                            TenVTPT = "Lọc nhớt K&N Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 115,
                            DonGia = 1065000m,
                            SoLuongTon = 19,
                            TenVTPT = "Lọc nhớt Mobil Loại 1"
                        },
                        new
                        {
                            MaVTPT = 116,
                            DonGia = 624000m,
                            SoLuongTon = 25,
                            TenVTPT = "Lọc nhớt Mobil Loại 2"
                        },
                        new
                        {
                            MaVTPT = 117,
                            DonGia = 1190000m,
                            SoLuongTon = 10,
                            TenVTPT = "Lọc nhớt Mobil Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 118,
                            DonGia = 1169000m,
                            SoLuongTon = 49,
                            TenVTPT = "Lọc nhớt Castrol Loại 1"
                        },
                        new
                        {
                            MaVTPT = 119,
                            DonGia = 206000m,
                            SoLuongTon = 20,
                            TenVTPT = "Lọc nhớt Castrol Loại 2"
                        },
                        new
                        {
                            MaVTPT = 120,
                            DonGia = 670000m,
                            SoLuongTon = 41,
                            TenVTPT = "Lọc nhớt Castrol Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 121,
                            DonGia = 1383000m,
                            SoLuongTon = 37,
                            TenVTPT = "Lọc gió Michelin Loại 1"
                        },
                        new
                        {
                            MaVTPT = 122,
                            DonGia = 456000m,
                            SoLuongTon = 22,
                            TenVTPT = "Lọc gió Michelin Loại 2"
                        },
                        new
                        {
                            MaVTPT = 123,
                            DonGia = 809000m,
                            SoLuongTon = 10,
                            TenVTPT = "Lọc gió Michelin Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 124,
                            DonGia = 1058000m,
                            SoLuongTon = 21,
                            TenVTPT = "Lọc gió Denso Loại 1"
                        },
                        new
                        {
                            MaVTPT = 125,
                            DonGia = 1387000m,
                            SoLuongTon = 19,
                            TenVTPT = "Lọc gió Denso Loại 2"
                        },
                        new
                        {
                            MaVTPT = 126,
                            DonGia = 586000m,
                            SoLuongTon = 26,
                            TenVTPT = "Lọc gió Denso Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 127,
                            DonGia = 1290000m,
                            SoLuongTon = 27,
                            TenVTPT = "Lọc gió Bosch Loại 1"
                        },
                        new
                        {
                            MaVTPT = 128,
                            DonGia = 428000m,
                            SoLuongTon = 40,
                            TenVTPT = "Lọc gió Bosch Loại 2"
                        },
                        new
                        {
                            MaVTPT = 129,
                            DonGia = 785000m,
                            SoLuongTon = 43,
                            TenVTPT = "Lọc gió Bosch Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 130,
                            DonGia = 1469000m,
                            SoLuongTon = 49,
                            TenVTPT = "Lọc gió Brembo Loại 1"
                        },
                        new
                        {
                            MaVTPT = 131,
                            DonGia = 880000m,
                            SoLuongTon = 25,
                            TenVTPT = "Lọc gió Brembo Loại 2"
                        },
                        new
                        {
                            MaVTPT = 132,
                            DonGia = 1184000m,
                            SoLuongTon = 42,
                            TenVTPT = "Lọc gió Brembo Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 133,
                            DonGia = 1259000m,
                            SoLuongTon = 29,
                            TenVTPT = "Lọc gió NGK Loại 1"
                        },
                        new
                        {
                            MaVTPT = 134,
                            DonGia = 518000m,
                            SoLuongTon = 29,
                            TenVTPT = "Lọc gió NGK Loại 2"
                        },
                        new
                        {
                            MaVTPT = 135,
                            DonGia = 1489000m,
                            SoLuongTon = 37,
                            TenVTPT = "Lọc gió NGK Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 136,
                            DonGia = 1050000m,
                            SoLuongTon = 28,
                            TenVTPT = "Lọc gió Yuasa Loại 1"
                        },
                        new
                        {
                            MaVTPT = 137,
                            DonGia = 1363000m,
                            SoLuongTon = 44,
                            TenVTPT = "Lọc gió Yuasa Loại 2"
                        },
                        new
                        {
                            MaVTPT = 138,
                            DonGia = 571000m,
                            SoLuongTon = 19,
                            TenVTPT = "Lọc gió Yuasa Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 139,
                            DonGia = 1010000m,
                            SoLuongTon = 34,
                            TenVTPT = "Lọc gió Varta Loại 1"
                        },
                        new
                        {
                            MaVTPT = 140,
                            DonGia = 1014000m,
                            SoLuongTon = 26,
                            TenVTPT = "Lọc gió Varta Loại 2"
                        },
                        new
                        {
                            MaVTPT = 141,
                            DonGia = 862000m,
                            SoLuongTon = 31,
                            TenVTPT = "Lọc gió Varta Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 142,
                            DonGia = 495000m,
                            SoLuongTon = 29,
                            TenVTPT = "Lọc gió K&N Loại 1"
                        },
                        new
                        {
                            MaVTPT = 143,
                            DonGia = 1308000m,
                            SoLuongTon = 10,
                            TenVTPT = "Lọc gió K&N Loại 2"
                        },
                        new
                        {
                            MaVTPT = 144,
                            DonGia = 806000m,
                            SoLuongTon = 24,
                            TenVTPT = "Lọc gió K&N Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 145,
                            DonGia = 1134000m,
                            SoLuongTon = 10,
                            TenVTPT = "Lọc gió Mobil Loại 1"
                        },
                        new
                        {
                            MaVTPT = 146,
                            DonGia = 724000m,
                            SoLuongTon = 21,
                            TenVTPT = "Lọc gió Mobil Loại 2"
                        },
                        new
                        {
                            MaVTPT = 147,
                            DonGia = 460000m,
                            SoLuongTon = 28,
                            TenVTPT = "Lọc gió Mobil Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 148,
                            DonGia = 341000m,
                            SoLuongTon = 32,
                            TenVTPT = "Lọc gió Castrol Loại 1"
                        },
                        new
                        {
                            MaVTPT = 149,
                            DonGia = 1346000m,
                            SoLuongTon = 30,
                            TenVTPT = "Lọc gió Castrol Loại 2"
                        },
                        new
                        {
                            MaVTPT = 150,
                            DonGia = 734000m,
                            SoLuongTon = 11,
                            TenVTPT = "Lọc gió Castrol Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 151,
                            DonGia = 1057000m,
                            SoLuongTon = 18,
                            TenVTPT = "Bình ắc quy Michelin Loại 1"
                        },
                        new
                        {
                            MaVTPT = 152,
                            DonGia = 453000m,
                            SoLuongTon = 20,
                            TenVTPT = "Bình ắc quy Michelin Loại 2"
                        },
                        new
                        {
                            MaVTPT = 153,
                            DonGia = 834000m,
                            SoLuongTon = 48,
                            TenVTPT = "Bình ắc quy Michelin Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 154,
                            DonGia = 756000m,
                            SoLuongTon = 10,
                            TenVTPT = "Bình ắc quy Denso Loại 1"
                        },
                        new
                        {
                            MaVTPT = 155,
                            DonGia = 162000m,
                            SoLuongTon = 11,
                            TenVTPT = "Bình ắc quy Denso Loại 2"
                        },
                        new
                        {
                            MaVTPT = 156,
                            DonGia = 174000m,
                            SoLuongTon = 47,
                            TenVTPT = "Bình ắc quy Denso Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 157,
                            DonGia = 281000m,
                            SoLuongTon = 33,
                            TenVTPT = "Bình ắc quy Bosch Loại 1"
                        },
                        new
                        {
                            MaVTPT = 158,
                            DonGia = 639000m,
                            SoLuongTon = 11,
                            TenVTPT = "Bình ắc quy Bosch Loại 2"
                        },
                        new
                        {
                            MaVTPT = 159,
                            DonGia = 158000m,
                            SoLuongTon = 22,
                            TenVTPT = "Bình ắc quy Bosch Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 160,
                            DonGia = 1387000m,
                            SoLuongTon = 44,
                            TenVTPT = "Bình ắc quy Brembo Loại 1"
                        },
                        new
                        {
                            MaVTPT = 161,
                            DonGia = 1438000m,
                            SoLuongTon = 49,
                            TenVTPT = "Bình ắc quy Brembo Loại 2"
                        },
                        new
                        {
                            MaVTPT = 162,
                            DonGia = 1115000m,
                            SoLuongTon = 49,
                            TenVTPT = "Bình ắc quy Brembo Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 163,
                            DonGia = 341000m,
                            SoLuongTon = 26,
                            TenVTPT = "Bình ắc quy NGK Loại 1"
                        },
                        new
                        {
                            MaVTPT = 164,
                            DonGia = 278000m,
                            SoLuongTon = 28,
                            TenVTPT = "Bình ắc quy NGK Loại 2"
                        },
                        new
                        {
                            MaVTPT = 165,
                            DonGia = 970000m,
                            SoLuongTon = 43,
                            TenVTPT = "Bình ắc quy NGK Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 166,
                            DonGia = 537000m,
                            SoLuongTon = 17,
                            TenVTPT = "Bình ắc quy Yuasa Loại 1"
                        },
                        new
                        {
                            MaVTPT = 167,
                            DonGia = 241000m,
                            SoLuongTon = 35,
                            TenVTPT = "Bình ắc quy Yuasa Loại 2"
                        },
                        new
                        {
                            MaVTPT = 168,
                            DonGia = 1093000m,
                            SoLuongTon = 24,
                            TenVTPT = "Bình ắc quy Yuasa Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 169,
                            DonGia = 421000m,
                            SoLuongTon = 12,
                            TenVTPT = "Bình ắc quy Varta Loại 1"
                        },
                        new
                        {
                            MaVTPT = 170,
                            DonGia = 1395000m,
                            SoLuongTon = 48,
                            TenVTPT = "Bình ắc quy Varta Loại 2"
                        },
                        new
                        {
                            MaVTPT = 171,
                            DonGia = 798000m,
                            SoLuongTon = 30,
                            TenVTPT = "Bình ắc quy Varta Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 172,
                            DonGia = 443000m,
                            SoLuongTon = 39,
                            TenVTPT = "Bình ắc quy K&N Loại 1"
                        },
                        new
                        {
                            MaVTPT = 173,
                            DonGia = 1410000m,
                            SoLuongTon = 33,
                            TenVTPT = "Bình ắc quy K&N Loại 2"
                        },
                        new
                        {
                            MaVTPT = 174,
                            DonGia = 229000m,
                            SoLuongTon = 39,
                            TenVTPT = "Bình ắc quy K&N Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 175,
                            DonGia = 129000m,
                            SoLuongTon = 16,
                            TenVTPT = "Bình ắc quy Mobil Loại 1"
                        },
                        new
                        {
                            MaVTPT = 176,
                            DonGia = 721000m,
                            SoLuongTon = 33,
                            TenVTPT = "Bình ắc quy Mobil Loại 2"
                        },
                        new
                        {
                            MaVTPT = 177,
                            DonGia = 873000m,
                            SoLuongTon = 36,
                            TenVTPT = "Bình ắc quy Mobil Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 178,
                            DonGia = 174000m,
                            SoLuongTon = 39,
                            TenVTPT = "Bình ắc quy Castrol Loại 1"
                        },
                        new
                        {
                            MaVTPT = 179,
                            DonGia = 742000m,
                            SoLuongTon = 22,
                            TenVTPT = "Bình ắc quy Castrol Loại 2"
                        },
                        new
                        {
                            MaVTPT = 180,
                            DonGia = 130000m,
                            SoLuongTon = 15,
                            TenVTPT = "Bình ắc quy Castrol Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 181,
                            DonGia = 1168000m,
                            SoLuongTon = 11,
                            TenVTPT = "Phuộc giảm xóc Michelin Loại 1"
                        },
                        new
                        {
                            MaVTPT = 182,
                            DonGia = 607000m,
                            SoLuongTon = 20,
                            TenVTPT = "Phuộc giảm xóc Michelin Loại 2"
                        },
                        new
                        {
                            MaVTPT = 183,
                            DonGia = 1056000m,
                            SoLuongTon = 47,
                            TenVTPT = "Phuộc giảm xóc Michelin Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 184,
                            DonGia = 1168000m,
                            SoLuongTon = 32,
                            TenVTPT = "Phuộc giảm xóc Denso Loại 1"
                        },
                        new
                        {
                            MaVTPT = 185,
                            DonGia = 1275000m,
                            SoLuongTon = 12,
                            TenVTPT = "Phuộc giảm xóc Denso Loại 2"
                        },
                        new
                        {
                            MaVTPT = 186,
                            DonGia = 1183000m,
                            SoLuongTon = 10,
                            TenVTPT = "Phuộc giảm xóc Denso Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 187,
                            DonGia = 608000m,
                            SoLuongTon = 50,
                            TenVTPT = "Phuộc giảm xóc Bosch Loại 1"
                        },
                        new
                        {
                            MaVTPT = 188,
                            DonGia = 506000m,
                            SoLuongTon = 28,
                            TenVTPT = "Phuộc giảm xóc Bosch Loại 2"
                        },
                        new
                        {
                            MaVTPT = 189,
                            DonGia = 1069000m,
                            SoLuongTon = 10,
                            TenVTPT = "Phuộc giảm xóc Bosch Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 190,
                            DonGia = 94000m,
                            SoLuongTon = 36,
                            TenVTPT = "Phuộc giảm xóc Brembo Loại 1"
                        },
                        new
                        {
                            MaVTPT = 191,
                            DonGia = 459000m,
                            SoLuongTon = 28,
                            TenVTPT = "Phuộc giảm xóc Brembo Loại 2"
                        },
                        new
                        {
                            MaVTPT = 192,
                            DonGia = 614000m,
                            SoLuongTon = 29,
                            TenVTPT = "Phuộc giảm xóc Brembo Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 193,
                            DonGia = 569000m,
                            SoLuongTon = 40,
                            TenVTPT = "Phuộc giảm xóc NGK Loại 1"
                        },
                        new
                        {
                            MaVTPT = 194,
                            DonGia = 926000m,
                            SoLuongTon = 30,
                            TenVTPT = "Phuộc giảm xóc NGK Loại 2"
                        },
                        new
                        {
                            MaVTPT = 195,
                            DonGia = 826000m,
                            SoLuongTon = 50,
                            TenVTPT = "Phuộc giảm xóc NGK Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 196,
                            DonGia = 1311000m,
                            SoLuongTon = 48,
                            TenVTPT = "Phuộc giảm xóc Yuasa Loại 1"
                        },
                        new
                        {
                            MaVTPT = 197,
                            DonGia = 1492000m,
                            SoLuongTon = 42,
                            TenVTPT = "Phuộc giảm xóc Yuasa Loại 2"
                        },
                        new
                        {
                            MaVTPT = 198,
                            DonGia = 292000m,
                            SoLuongTon = 29,
                            TenVTPT = "Phuộc giảm xóc Yuasa Cao cấp"
                        },
                        new
                        {
                            MaVTPT = 199,
                            DonGia = 221000m,
                            SoLuongTon = 10,
                            TenVTPT = "Phuộc giảm xóc Varta Loại 1"
                        },
                        new
                        {
                            MaVTPT = 200,
                            DonGia = 83000m,
                            SoLuongTon = 11,
                            TenVTPT = "Phuộc giảm xóc Varta Loại 2"
                        });
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.Xe", b =>
                {
                    b.Property<int>("MaXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXe"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHieuXe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChuXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TienNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.HasKey("MaXe");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.HasIndex("MaHieuXe");

                    b.ToTable("XE");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("DanhSachCTPhieuNhap")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGaraOto.Models.VatTuPhuTung", "VatTuPhuTung")
                        .WithMany("DanhSachCTPhieuNhap")
                        .HasForeignKey("MaVTPT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("VatTuPhuTung");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.ChiTietPhieuSuaChua", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.PhieuSuaChua", "PhieuSuaChua")
                        .WithMany("DanhSachCTPhieuSuaChua")
                        .HasForeignKey("MaPhieuSuaChua")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGaraOto.Models.TienCong", "TienCong")
                        .WithMany("DanhSachCTPhieuSuaChua")
                        .HasForeignKey("MaTienCong")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyGaraOto.Models.VatTuPhuTung", "VatTuPhuTung")
                        .WithMany("DanhSachCTPhieuSuaChua")
                        .HasForeignKey("MaVTPT")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhieuSuaChua");

                    b.Navigation("TienCong");

                    b.Navigation("VatTuPhuTung");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.VaiTro", "VaiTro")
                        .WithMany("DanhSachNguoiDung")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuSuaChua", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.Xe", "Xe")
                        .WithMany("DanhSachPhieuSuaChua")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuThuTien", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.Xe", "Xe")
                        .WithMany("DanhSachPhieuThuTien")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.Xe", b =>
                {
                    b.HasOne("QuanLyGaraOto.Models.HieuXe", "HieuXe")
                        .WithMany("DanhSachXe")
                        .HasForeignKey("MaHieuXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HieuXe");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.HieuXe", b =>
                {
                    b.Navigation("DanhSachXe");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuNhap", b =>
                {
                    b.Navigation("DanhSachCTPhieuNhap");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.PhieuSuaChua", b =>
                {
                    b.Navigation("DanhSachCTPhieuSuaChua");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.TienCong", b =>
                {
                    b.Navigation("DanhSachCTPhieuSuaChua");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.VaiTro", b =>
                {
                    b.Navigation("DanhSachNguoiDung");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.VatTuPhuTung", b =>
                {
                    b.Navigation("DanhSachCTPhieuNhap");

                    b.Navigation("DanhSachCTPhieuSuaChua");
                });

            modelBuilder.Entity("QuanLyGaraOto.Models.Xe", b =>
                {
                    b.Navigation("DanhSachPhieuSuaChua");

                    b.Navigation("DanhSachPhieuThuTien");
                });
#pragma warning restore 612, 618
        }
    }
}
